import { Link } from 'react-router-dom'
import { FiArrowUpRight } from 'react-icons/fi'
import Seo from '../components/Seo.jsx'
import Breadcrumbs from '../components/Breadcrumbs.jsx'
import Reveal from '../components/Reveal.jsx'

export const insights = [
['small-business-website-development-process-timeline-cost','Small Business Website Development: Process, Timeline and Cost','BOFU','A practical guide to the stages, decisions and cost drivers behind a small-business website project.'],
['custom-website-vs-template','Custom Website vs Template: Which Is Right for a Small Business?','Comparison','Compare control, flexibility, maintenance and fit before choosing a website approach.'],
['website-redesign-checklist','Website Redesign Checklist: 25 Signs It Is Time','BOFU','A checklist for spotting usability, content, performance and conversion problems in an aging website.'],
['how-much-website-maintenance-costs-2026','How Much Does Website Maintenance Cost in 2026?','Commercial research','Understand the factors that shape ongoing website maintenance and support costs.'],
['react-vs-wordpress-small-business','React vs WordPress for a Small-Business Website','Comparison','A buyer-focused comparison of flexibility, content management, performance and maintenance.'],
['ecommerce-website-cost-checklist','Ecommerce Website Cost and Feature Checklist','BOFU','A practical checklist for planning ecommerce functionality, integrations and launch scope.'],
['website-accessibility-basics','Website Accessibility Basics for Small Businesses','Helpful guide','A straightforward introduction to accessible navigation, content, forms and interfaces.'],
['how-to-choose-web-development-company','How to Choose a Web Development Company: 15 Questions','Commercial research','Questions to ask before selecting a development partner for a business website or web app.'],
['small-business-website-performance-benchmark-2026','2026 Small-Business Website Performance Benchmark','Research','A future original-research asset template for measuring performance across small-business websites.'],
]

export function InsightArticle({ slug }) {
 const item=insights.find(x=>x[0]===slug); if(!item) return null
 const sections={
  'small-business-website-development-process-timeline-cost':[['1. Discovery','Clarify the business goal, target customers, existing website constraints, required pages, integrations and the primary conversion action.'],['2. Structure and content','Plan the information architecture before visual design. Service pages, proof, FAQs and contact paths should help a visitor understand the offer and take the next step.'],['3. Design and development','Build responsive layouts, reusable components, accessible interactions and the functionality required for the agreed scope.'],['4. Testing and launch','Test navigation, forms, responsive layouts, metadata, redirects, performance and key user journeys before launch.'],['5. Support and improvement','Post-launch support can cover fixes, content updates, technical maintenance and measured improvements as real search and user data becomes available.']],
  'custom-website-vs-template':[['Control and fit','A custom build can be shaped around specific workflows and content needs. A template can be faster when the requirements are simple and the available structure already fits.'],['Content and conversion','The better choice is the one that makes it easier to communicate the offer and guide the visitor toward the desired action.'],['Maintenance','Consider who will update the site, how integrations will be maintained and whether the chosen stack can be supported over time.'],['Performance and accessibility','Regardless of the approach, the final implementation should be tested for mobile usability, accessibility and performance.'],['Decision rule','Choose based on requirements and total ownership cost rather than technology preference alone.']],
  'website-redesign-checklist':[['Content problems','Look for outdated services, unclear value propositions, weak headings, duplicated content and missing calls to action.'],['UX problems','Check navigation, forms, mobile layouts, page hierarchy and whether important information is easy to find.'],['Trust problems','Review proof, case studies, testimonials, contact information and signals that help a buyer feel confident.'],['Technical problems','Check redirects, canonical URLs, indexability, image dimensions, performance and broken links before rebuilding.'],['Conversion problems','Identify pages with traffic but weak next steps, then redesign around the buyer journey rather than visual novelty.']],
  'how-much-website-maintenance-costs-2026':[['Scope','Maintenance can mean small content updates, bug fixes, dependency updates, monitoring or ongoing development. Define what is included.'],['Response expectations','Faster response requirements and active development support generally require more capacity than occasional updates.'],['Platform complexity','Custom applications, integrations and older codebases can require more technical review than a simple brochure site.'],['Preventive work','Regular updates and technical checks can reduce the chance that small issues become larger launch or security problems.'],['Budgeting','Ask for a clear support scope and exclusions instead of comparing maintenance prices without comparing what is actually delivered.']],
  'react-vs-wordpress-small-business':[['Content management','Consider who will publish and edit content and how frequently the business needs to make changes.'],['Custom functionality','Complex interactive experiences can benefit from a custom application architecture; simpler content-led sites may not need that complexity.'],['Performance','The implementation quality matters more than the framework name. Test the actual site rather than assuming a stack is automatically fast.'],['Maintenance','Evaluate hosting, updates, dependencies, plugins, code ownership and who will support the site after launch.'],['Choosing well','Pick the simplest platform that satisfies the real requirements while leaving room for the expected next stage.']],
  'ecommerce-website-cost-checklist':[['Catalog','Plan products, variants, categories, filters, images, inventory and content before estimating development work.'],['Checkout','Define payment methods, shipping, taxes, customer accounts and confirmation flows required for launch.'],['Integrations','List external systems such as fulfillment, CRM, email, analytics and inventory connections.'],['SEO','Plan crawlable category/product paths, metadata, internal links, useful product content and redirects for migrations.'],['Operations','Include order management, support, updates and ownership in the project plan—not only the storefront.']],
  'website-accessibility-basics':[['Keyboard access','Interactive controls should be reachable and understandable without a mouse.'],['Content structure','Use meaningful headings, labels and link text so users can understand the page structure.'],['Forms','Labels, focus states, validation messages and clear error handling are important for usable forms.'],['Contrast and readability','Text and controls should remain legible against the visual design across screen sizes.'],['Testing','Combine automated checks with keyboard, mobile and assistive-technology testing where practical.']],
  'how-to-choose-web-development-company':[['Ask about process','A good partner should explain discovery, scope, milestones, testing, launch and support in understandable language.'],['Ask about ownership','Clarify code ownership, hosting, accounts, domains, analytics and how handoff works after launch.'],['Ask for relevant proof','Look for case studies that match the type of business problem you need solved, not just attractive screenshots.'],['Ask about support','Understand response expectations, maintenance, revisions and what happens after launch.'],['Ask about measurement','Agree on meaningful outcomes and how progress will be evaluated instead of relying only on vanity metrics.']],
  'small-business-website-performance-benchmark-2026':[['Methodology first','A useful benchmark needs a clearly defined sample, consistent test conditions and documented methodology.'],['Measures','Consider loading performance, Core Web Vitals, page weight, image handling, mobile usability and technical implementation.'],['Segmentation','Separate industries, site types and technology patterns so comparisons are meaningful.'],['Interpretation','Benchmarks should inform priorities rather than become arbitrary pass/fail claims.'],['Publishing','Explain the methodology and limitations so the research can be trusted and cited by others.']]
 }[slug]||[]
 return <><Seo path={`/insights/${slug}`} /><Breadcrumbs items={[{label:'Insights',to:'/insights'},{label:item[1]}]} /><article className="pt-10 pb-24"><div className="max-w-3xl mx-auto section-pad"><Reveal><span className="eyebrow">{item[2]}</span><h1 className="mt-5 font-display text-4xl sm:text-6xl font-semibold tracking-tight leading-[1]">{item[1]}</h1><p className="mt-7 text-lg leading-8 text-white/55">{item[3]}</p></Reveal><div className="mt-12 space-y-5">{sections.map(([h,b])=><Reveal key={h}><section className="card-dark p-7"><h2 className="font-display text-2xl font-semibold text-white">{h}</h2><p className="mt-4 text-white/45 leading-7">{b}</p></section></Reveal>)}</div><div className="mt-12 rounded-2xl border border-blue-400/20 bg-blue-500/[.05] p-7"><h2 className="font-display text-2xl font-semibold text-white">Need help with this for your business?</h2><p className="mt-3 text-white/45">S.A.T Solution can help turn the question into a scoped project.</p><Link to="/contact" className="mt-6 inline-flex items-center gap-2 rounded-full bg-blue-500 px-6 py-3 text-sm font-semibold text-white">Talk to S.A.T Solution <FiArrowUpRight/></Link></div></div></article></>
}

export default function InsightsPage(){return <><Seo path="/insights"/><Breadcrumbs items={[{label:'Insights'}]}/><section className="pt-10 pb-20 md:pb-28"><div className="max-w-content mx-auto section-pad"><Reveal><span className="eyebrow">Knowledge</span><h1 className="mt-4 font-display text-4xl sm:text-6xl font-semibold tracking-tight">Insights for better digital decisions.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/50">Practical guidance for small businesses planning websites, web applications, redesigns, ecommerce and ongoing support.</p></Reveal><div className="mt-12 grid md:grid-cols-2 lg:grid-cols-3 gap-4">{insights.map((x,i)=><Reveal key={x[0]} delay={i*35}><Link to={`/insights/${x[0]}`} className="card-dark card-dark-hover p-7 block h-full"><span className="eyebrow">{x[2]}</span><h2 className="mt-5 font-display text-xl font-semibold">{x[1]}</h2><p className="mt-3 text-sm leading-6 text-white/45">{x[3]}</p><span className="mt-7 inline-flex items-center gap-2 text-sm text-blue-300">Read guide <FiArrowUpRight/></span></Link></Reveal>)}</div></div></section></>}
