import { Link } from 'react-router-dom'
import Seo from '../components/Seo.jsx'
import Breadcrumbs from '../components/Breadcrumbs.jsx'
import Reveal from '../components/Reveal.jsx'

export function TeamPage(){return <><Seo path="/team"/><Breadcrumbs items={[{label:'Team'}]}/><section className="pt-10 pb-28"><div className="max-w-content mx-auto section-pad"><Reveal><span className="eyebrow">Team</span><h1 className="mt-4 font-display text-4xl sm:text-6xl font-semibold">A practical development team behind the work.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/50">S.A.T Solution combines strategy, design and engineering around the requirements of each engagement.</p></Reveal><div className="mt-12 card-dark p-8 md:p-10"><h2 className="font-display text-2xl font-semibold">Team profiles</h2><p className="mt-4 max-w-2xl text-white/45 leading-7">Individual names, roles, headshots and professional profiles should be added here from your verified company information. This page intentionally does not invent team identities.</p></div></div></section></>}

const legal = {
 '/privacy-policy': ['Privacy Policy','This page provides a plain-language outline of how information submitted through the S.A.T Solution website may be used.',[['Information you submit','We may receive information such as your name, email address and project details when you contact S.A.T Solution.'],['How information is used','Submitted information may be used to respond to enquiries, scope projects and provide requested support.'],['Third parties','Any third-party services used for forms, analytics, hosting or communication should be listed here after confirming the actual services in production.']]],
 '/terms': ['Terms of Use','These terms describe general use of the S.A.T Solution website. They should be reviewed and adapted to your actual legal and commercial arrangements before publication as final terms.',[['Website use','Use the website lawfully and do not attempt to disrupt or misuse its services.'],['Project agreements','Actual project scope, payment, intellectual property, support and delivery terms should be governed by the signed agreement for each engagement.'],['Content','Website content should not be treated as a guarantee of a particular business result.']]],
 '/accessibility': ['Accessibility Statement','S.A.T Solution aims to make its digital experiences usable across devices and accessible to as many people as practical.',[['Keyboard access','Interactive controls should remain reachable and understandable with keyboard navigation.'],['Visual clarity','The site uses readable type, focus states and contrast-aware dark interfaces.'],['Ongoing improvement','Accessibility issues can be reported through the Contact page so they can be reviewed and addressed.']]]
}
export function LegalPage({path}){const [h,intro,sections]=legal[path];return <><Seo path={path}/><Breadcrumbs items={[{label:h}]}/><section className="pt-10 pb-28"><div className="max-w-3xl mx-auto section-pad"><Reveal><span className="eyebrow">S.A.T Solution</span><h1 className="mt-4 font-display text-4xl sm:text-6xl font-semibold">{h}</h1><p className="mt-6 text-lg leading-8 text-white/50">{intro}</p></Reveal><div className="mt-12 space-y-8">{sections.map(([title,body])=><Reveal key={title}><section className="card-dark p-7"><h2 className="font-display text-2xl font-semibold">{title}</h2><p className="mt-4 text-white/45 leading-7">{body}</p></section></Reveal>)}</div><p className="mt-10 text-sm text-white/35">Questions about this page? <Link to="/contact" className="text-blue-300">Contact S.A.T Solution.</Link></p></div></section></>}
