// NOTE: prices below are placeholders so the section has real structure —
// edit them (and the feature lists) to match S.A.T Solution's actual rates.
export const packageCategories = [
  {
    id: 'web',
    label: 'Web Development',
    icon: 'globe',
    tiers: [
      {
        name: 'Starter Website',
        tagline: 'Perfect for small businesses and startups',
        price: '$350',
        priceNote: '/one-time',
        features: [
          'Up to 5 pages',
          'Responsive design',
          'Contact form integration',
          'Basic SEO optimization',
          'Fast loading speed',
          'Launch & support',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Professional Website',
        tagline: 'Ideal for growing businesses',
        price: '$650',
        priceNote: '/one-time',
        popular: true,
        features: [
          'Everything in Starter +',
          '8+ pages',
          'Custom design',
          'Advanced SEO optimization',
          'CMS integration',
          'Blog functionality',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Custom Solution',
        tagline: 'Tailored to your unique needs',
        price: "Let's Talk",
        features: [
          'Everything in Professional +',
          'Unlimited pages',
          'E-commerce ready',
          'Custom features & integrations',
          'Dedicated project manager',
        ],
        cta: 'Contact Us',
      },
    ],
  },
  {
    id: 'mobile',
    label: 'Mobile App Development',
    icon: 'phone',
    tiers: [
      {
        name: 'Starter App',
        tagline: 'A focused app for a single platform',
        price: '$800',
        priceNote: '/one-time',
        features: [
          'iOS or Android (single platform)',
          'Up to 4 screens',
          'Basic UI design',
          'App store submission support',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Professional App',
        tagline: 'Cross-platform, ready to scale',
        price: '$1,500',
        priceNote: '/one-time',
        popular: true,
        features: [
          'iOS & Android (cross-platform)',
          'Up to 10 screens',
          'Custom UI/UX design',
          'API integration',
          'Push notifications',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Custom Solution',
        tagline: 'Enterprise-grade mobile products',
        price: "Let's Talk",
        features: [
          'Unlimited screens',
          'Backend & admin panel',
          'Third-party integrations',
          'Ongoing maintenance',
        ],
        cta: 'Contact Us',
      },
    ],
  },
  {
    id: 'cloud',
    label: 'Cloud & IT Consulting',
    icon: 'cloud',
    tiers: [
      {
        name: 'Starter',
        tagline: 'Get your infrastructure assessed',
        price: '$250',
        priceNote: '/one-time',
        features: [
          'Cloud readiness assessment',
          'Basic deployment setup',
          'Setup documentation',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Professional',
        tagline: 'Ongoing, managed infrastructure',
        price: '$500',
        priceNote: '/month',
        popular: true,
        features: [
          'Managed cloud infrastructure',
          'Performance monitoring',
          'Monthly strategy review',
          'Priority support',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Custom Solution',
        tagline: 'Multi-cloud, enterprise scale',
        price: "Let's Talk",
        features: [
          'Multi-cloud architecture',
          'Dedicated IT consultant',
          '24/7 support',
        ],
        cta: 'Contact Us',
      },
    ],
  },
  {
    id: 'automation',
    label: 'Business Automation',
    icon: 'zap',
    tiers: [
      {
        name: 'Starter',
        tagline: 'Automate one workflow',
        price: '$300',
        priceNote: '/one-time',
        features: [
          'One workflow automated',
          'Basic tool integrations',
          'Setup & training',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Professional',
        tagline: 'Automate across your business',
        price: '$700',
        priceNote: '/one-time',
        popular: true,
        features: [
          'Up to 5 workflows automated',
          'Cross-tool integrations',
          'Reporting dashboard',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Custom Solution',
        tagline: 'Enterprise-level automation',
        price: "Let's Talk",
        features: [
          'Enterprise automation',
          'Custom integrations',
          'Ongoing optimization',
        ],
        cta: 'Contact Us',
      },
    ],
  },
  {
    id: 'creative',
    label: 'Creative & Digital',
    icon: 'layers',
    tiers: [
      {
        name: 'Starter',
        tagline: 'Consistent presence, made simple',
        price: '$200',
        priceNote: '/month',
        features: [
          'Social media management (2 platforms)',
          '12 posts / month',
          'Basic performance reporting',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Professional',
        tagline: 'Content + video, on a schedule',
        price: '$450',
        priceNote: '/month',
        popular: true,
        features: [
          'Social media + video editing',
          '20 posts / month',
          'Content calendar',
          'Monthly performance reporting',
        ],
        cta: 'Get Started',
      },
      {
        name: 'Custom Solution',
        tagline: 'A full creative team, on demand',
        price: "Let's Talk",
        features: [
          'Full-service digital marketing',
          'Dedicated creative team',
          'Custom campaigns',
        ],
        cta: 'Contact Us',
      },
    ],
  },
]
